// BACKUP: lightweight marker for legacy `src/app.js` before staged migration.
// The full legacy file was large and previously concatenated/duplicated; a
// complete copy is available in Git history. This marker indicates a backup
// step was intentionally taken before we perform a staged migration.

export const legacyBackup = true;
// Backup of previous src/app.js (legacy). Kept for staged migration.
// Do not edit this file directly; it's a snapshot for migration.

/*
  Legacy file contents trimmed in backup to reduce size in repo.
  Full original content is preserved in repository history if needed.
*/

export const LEGACY_APP_BACKUP = true;
